### ISSUE TITLE
Bug loading CAMB Cls

### ISSUE THREAD

**Issue by pdp79** [marius311/CMBLensing.jl#1]
Hi,

I was playing around with CMBLensing.jl and I have found a bug in the 'load_camb_Cls()' function.

If you do try to read some CAMB file and you enter in the 'else' clause of the 'custom_tensor_params != nothing' condition (starting at line 221 on CMBLensing.jl/cls.jl), you would find that neither the 'tensor_filename' or 'r' variables have been previously defined, raising you an error that kills the code.
 
Maybe you meant to use 'unlensed_tensor_filename' (defined at line 197) instead of 'tensor_filename'?

**Comment by marius311** [comment]
Just pushed a fix, thanks for catching that!
