### ISSUE TITLE
passing operators to `load_sim_dataset` is delicate on v0.2.1

### ISSUE THREAD

**Issue by cailmdaley** [marius311/CMBLensing.jl#13]
passing `M̂=1` or `B=1` to `load_sim_dataset` causes dataset creation to fail, and passing `L=Identity` causes `resimulate!` to fail.

**Comment by marius311** [comment]
Should be fixed by https://github.com/marius311/CMBLensing.jl/commit/c945d67ad5b17cff7c7da070e4bcb9a657477b47 let  me know if you run into issues. 

You can now just pass `1` to any of `M`, `B`, `L`, or their `\hat` variants.
